export default [
  {
    user_level_require: 3,
    name: "Бодрящий ланч",
    duration: 45,
    instant_energy_restore: null,
    long_energy_restore: {
      value: 180,
      percent: false,
    },
    instant_hungry_restore: {
      value: 1,
      percent: true,
    },
    long_hungry_restore: null,
    instant_mood_restore: null,
    long_mood_restore: null,
    coins_price: 400,
    link: "https://13floorgame.ru/images/foods/liteLunch.png",
    food_id: 3,
  },
  {
    user_level_require: 10,
    name: "Стейк",
    duration: 50,
    instant_energy_restore: null,
    long_energy_restore: null,
    instant_hungry_restore: {
      value: 16,
      percent: true,
    },
    long_hungry_restore: {
      value: 2,
      percent: true,
    },
    instant_mood_restore: null,
    long_mood_restore: null,
    coins_price: 1000,
    link: "https://13floorgame.ru/images/foods/steak.png",
    food_id: 6,
  },
  {
    user_level_require: 2,
    name: "Сытный бургер",
    duration: 50,
    instant_energy_restore: null,
    long_energy_restore: null,
    instant_hungry_restore: {
      value: 5,
      percent: true,
    },
    long_hungry_restore: {
      value: 0.5,
      percent: true,
    },
    instant_mood_restore: null,
    long_mood_restore: null,
    coins_price: 200,
    link: "https://13floorgame.ru/images/foods/burger.png",
    food_id: 2,
  },
  {
    user_level_require: 14,
    name: "Буррито",
    duration: 45,
    instant_energy_restore: null,
    long_energy_restore: {
      value: 50,
      percent: false,
    },
    instant_hungry_restore: {
      value: 25,
      percent: true,
    },
    long_hungry_restore: null,
    instant_mood_restore: null,
    long_mood_restore: null,
    coins_price: 1800,
    link: "https://13floorgame.ru/images/foods/burrito.png",
    food_id: 8,
  },
  {
    user_level_require: 1,
    name: "Яблоко",
    duration: 20,
    instant_energy_restore: null,
    long_energy_restore: null,
    instant_hungry_restore: {
      value: 1.5,
      percent: true,
    },
    long_hungry_restore: null,
    instant_mood_restore: null,
    long_mood_restore: null,
    coins_price: 50,
    link: "https://13floorgame.ru/images/foods/apple.png",
    food_id: 1,
  },
  {
    user_level_require: 12,
    name: "Суши",
    duration: 200,
    instant_energy_restore: null,
    long_energy_restore: null,
    instant_hungry_restore: {
      value: 7,
      percent: true,
    },
    long_hungry_restore: null,
    instant_mood_restore: null,
    long_mood_restore: {
      value: 5,
      percent: true,
    },
    coins_price: 1400,
    link: "https://13floorgame.ru/images/foods/sushi.png",
    food_id: 7,
  },
  {
    user_level_require: 6,
    name: "Протеиновый батончик",
    duration: 120,
    instant_energy_restore: null,
    long_energy_restore: null,
    instant_hungry_restore: {
      value: 15,
      percent: true,
    },
    long_hungry_restore: null,
    instant_mood_restore: null,
    long_mood_restore: null,
    coins_price: 750,
    link: "https://13floorgame.ru/images/foods/proteinBar.png",
    food_id: 5,
  },
  {
    user_level_require: 4,
    name: "Комплексный обед",
    duration: 80,
    instant_energy_restore: null,
    long_energy_restore: null,
    instant_hungry_restore: {
      value: 10,
      percent: true,
    },
    long_hungry_restore: {
      value: 1.5,
      percent: true,
    },
    instant_mood_restore: null,
    long_mood_restore: null,
    coins_price: 600,
    link: "https://13floorgame.ru/images/foods/lunch.png",
    food_id: 4,
  },
]
