export default [
  {
    skill_id: 1,
    name: "Мотивирующий подкаст",
    coins_price: 1,
    description: null,
    duration: 1,
    skill_id_required: null,
    type: null,
    link: "https://13floorgame.ru/images/skills/podcast.png",
  },
  {
    skill_id: 2,
    name: "Спортивная одежда",
    coins_price: 1,
    description:
      "Если во время тренировки вы одеты в спортивную одежду, вы восстанавливаете больше счастья после тренировки",
    duration: 30,
    skill_id_required: null,
    type: null,
    link: "https://13floorgame.ru/images/skills/sportswear.png",
  },
  {
    skill_id: 3,
    name: "Офисные программы",
    coins_price: 1,
    description: "Изучите базовые офисные программы для продвижения по работе",
    duration: 120,
    skill_id_required: 1,
    type: null,
    link: "https://13floorgame.ru/images/skills/officePrograms.png",
  },
  {
    skill_id: 4,
    name: "Онлайн обучение",
    coins_price: 1,
    description: null,
    duration: 200,
    skill_id_required: 3,
    type: null,
    link: "https://13floorgame.ru/images/skills/onlineLearning.png",
  },
  {
    skill_id: 5,
    name: "Тренинг по рекламе",
    coins_price: 1,
    description: null,
    duration: 300,
    skill_id_required: 4,
    type: null,
    link: "https://13floorgame.ru/images/skills/advertising.png",
  },
  {
    skill_id: 6,
    name: "Курсы подбора персонала",
    coins_price: 1,
    description: null,
    duration: 450,
    skill_id_required: 5,
    type: null,
    link: "https://13floorgame.ru/images/skills/recrutCourses.png",
  },
  {
    skill_id: 7,
    name: "Статья о здоровом сне",
    coins_price: 1,
    description:
      "Твой сон длится меньше на 30 минут, но ты чувствуешь себя все так же бодро",
    duration: 500,
    skill_id_required: null,
    type: null,
    link: "https://13floorgame.ru/images/skills/sleepMode.png",
  },
  {
    skill_id: 8,
    name: "Школа менеджмента",
    coins_price: 1,
    description: null,
    duration: 675,
    skill_id_required: 6,
    type: null,
    link: "https://13floorgame.ru/images/skills/management.png",
  },
  {
    skill_id: 9,
    name: "Бизнес тренинг",
    coins_price: 1,
    description: null,
    duration: 1050,
    skill_id_required: 8,
    type: null,
    link: "https://13floorgame.ru/images/skills/businessTraining.png",
  },
  {
    skill_id: 10,
    name: "Тренинг по автоматизации",
    coins_price: 1,
    description: null,
    duration: 1500,
    skill_id_required: 9,
    type: null,
    link: "https://13floorgame.ru/images/skills/automationTraining.png",
  },
  {
    skill_id: 12,
    name: "Энциклопедия бодибилдинга",
    coins_price: 1,
    description: "Твое настроение после тренировки улучшается на 10% больше",
    duration: 1800,
    skill_id_required: null,
    type: null,
    link: "https://13floorgame.ru/images/skills/bodybuilding.png",
  },
  {
    skill_id: 11,
    name: "Экономическое образование",
    coins_price: 1,
    description: null,
    duration: 2200,
    skill_id_required: 10,
    type: null,
    link: "https://13floorgame.ru/images/skills/economicEducation.png",
  },
]
