export default [
  {
    level: 1,
    duration: 1,
    energy_spend: 0.83,
    hungry_spend: 0.02,
    mood_profit: 2,
  },
  {
    level: 2,
    duration: 5,
    energy_spend: 2,
    hungry_spend: 0.04,
    mood_profit: 4,
  },
  {
    level: 3,
    duration: 10,
    energy_spend: 3,
    hungry_spend: 0.06,
    mood_profit: 8,
  },
  {
    level: 4,
    duration: 14,
    energy_spend: 4,
    hungry_spend: 0.08,
    mood_profit: 12,
  },
  {
    level: 5,
    duration: 18,
    energy_spend: 5,
    hungry_spend: 0.1,
    mood_profit: 14,
  },
  {
    level: 6,
    duration: 22,
    energy_spend: 5.83,
    hungry_spend: 0.12,
    mood_profit: 18,
  },
  {
    level: 7,
    duration: 27,
    energy_spend: 6.67,
    hungry_spend: 0.13,
    mood_profit: 20,
  },
  {
    level: 8,
    duration: 30,
    energy_spend: 7,
    hungry_spend: 0.14,
    mood_profit: 22,
  },
  {
    level: 9,
    duration: 35,
    energy_spend: 8,
    hungry_spend: 0.14,
    mood_profit: 28,
  },
  {
    level: 10,
    duration: 40,
    energy_spend: 9,
    hungry_spend: 0.15,
    mood_profit: 30,
  },
  {
    level: 12,
    duration: 48,
    energy_spend: 11,
    hungry_spend: 0.16,
    mood_profit: 34,
  },
  {
    level: 13,
    duration: 50,
    energy_spend: 12,
    hungry_spend: 0.17,
    mood_profit: 36,
  },
  {
    level: 14,
    duration: 55,
    energy_spend: 13,
    hungry_spend: 0.18,
    mood_profit: 38,
  },
  {
    level: 11,
    duration: 43,
    energy_spend: 10,
    hungry_spend: 0.15,
    mood_profit: 32,
  },
  {
    level: 15,
    duration: 60,
    energy_spend: 13.33,
    hungry_spend: 0.2,
    mood_profit: 40,
  },
]
