export default [
  {
    level: 1,
    duration: 1,
    energy_spend: 40,
    hungry_spend: 2,
    mood_profit: 40,
  },
  {
    level: 2,
    duration: 2,
    energy_spend: 50,
    hungry_spend: 1,
    mood_profit: 42,
  },
  {
    level: 3,
    duration: 5,
    energy_spend: 30,
    hungry_spend: 0.6,
    mood_profit: 44,
  },
  {
    level: 4,
    duration: 8,
    energy_spend: 30,
    hungry_spend: 0.5,
    mood_profit: 46,
  },
  {
    level: 5,
    duration: 10,
    energy_spend: 30,
    hungry_spend: 0.5,
    mood_profit: 48,
  },
  {
    level: 6,
    duration: 15,
    energy_spend: 30,
    hungry_spend: 0.4,
    mood_profit: 50,
  },
  {
    level: 7,
    duration: 18,
    energy_spend: 30,
    hungry_spend: 0.5,
    mood_profit: 52,
  },
  {
    level: 8,
    duration: 20,
    energy_spend: 30,
    hungry_spend: 0.4,
    mood_profit: 56,
  },
  {
    level: 9,
    duration: 22,
    energy_spend: 30,
    hungry_spend: 0.5,
    mood_profit: 60,
  },
  {
    level: 10,
    duration: 24,
    energy_spend: 30,
    hungry_spend: 0.5,
    mood_profit: 62,
  },
  {
    level: 11,
    duration: 26,
    energy_spend: 30,
    hungry_spend: 0.6,
    mood_profit: 64,
  },
  {
    level: 12,
    duration: 28,
    energy_spend: 35,
    hungry_spend: 0.75,
    mood_profit: 68,
  },
  {
    level: 13,
    duration: 30,
    energy_spend: 35,
    hungry_spend: 0.8,
    mood_profit: 72,
  },
  {
    level: 14,
    duration: 32,
    energy_spend: 10,
    hungry_spend: 1,
    mood_profit: 76,
  },
  {
    level: 15,
    duration: 34,
    energy_spend: 35,
    hungry_spend: 1.6,
    mood_profit: 80,
  },
]
