networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  database:
    image: mongo:5
    volumes:
      - db-floor:/data/db
      - ./restore-folder:/data/restore
    ports:
      - 27017:27017
    command: mongod --replSet rs0 --bind_ip_all
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
    # Add entrypoint to initialize replica set
    entrypoint: >
      /bin/bash -c "
      mongod --replSet rs0 --bind_ip_all & 
      sleep 5 && 
      mongo --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"localhost:27017\"}]})' && 
      wait"

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    command: redis-server --requirepass redis_password
    networks:
      - default

volumes:
  db-floor:
  redis-data: