networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  database:
    image: mongo:5
    volumes:
      - db-floor:/data/db
      - ./restore-folder:/data/restore
    ports:
      - 27017:27017
volumes:
  db-floor:
