networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  database:
    image: mongo:5
    volumes:
      - db-floor:/data/db
      - ./restore-folder:/data/restore
    ports:
      - 27017:27017

  redis:
    image: redis:7  # Using Redis 7, but you can adjust the version
    volumes:
      - redis-data:/data  # Persistent storage for Redis
    ports:
      - 6379:6379  # Default Redis port
    command: redis-server --requirepass redis_password  # Optional: Add a password
    networks:
      - default  # Explicitly attach to the default network

volumes:
  db-floor:
  redis-data: