export default [
  {
    work_id: 1,
    name: {
      ru: "Курьер",
      en: "Courier"
    },
    requiredLevel: 1,
    coins_price: 1,
    coins_in_hour: 60,
    energy_cost_in_hour: 250,
    mood_cost_in_hour: 60,
    hungry_cost_in_hour: 50,
    skill_id_required: null,
    respect_required: 50,
    link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/icons%2F%D0%BA%D1%83%D1%80%D1%8C%D0%B5%D1%80.png",
  },
  {
    work_id: 2,
    name: {
      ru: "Официант",
      en: "Waiter"
    },
    requiredLevel: 2,
    coins_price: 1,
    coins_in_hour: 120,
    energy_cost_in_hour: 300,
    mood_cost_in_hour: 80,
    hungry_cost_in_hour: 55,
    skill_id_required: 1,
    respect_required: 150,
    link: "https://13floorgame.ru/images/works/waiter.png",
  },
  {
    work_id: 3,
    name: {
      ru: "Офис-менеджер",
      en: "Office Manager"
    },
    requiredLevel: 3,
    coins_price: 1,
    coins_in_hour: 180,
    energy_cost_in_hour: 480,
    mood_cost_in_hour: 33,
    hungry_cost_in_hour: 60,
    skill_id_required: 3,
    respect_required: 200,
    link: "https://13floorgame.ru/images/works/officeManager.png",
  },
  {
    work_id: 4,
    name: {
      ru: "Администратор",
      en: "Administrator"
    },
    requiredLevel: 4,
    coins_price: 1,
    coins_in_hour: 240,
    energy_cost_in_hour: 650,
    mood_cost_in_hour: 38,
    hungry_cost_in_hour: 63,
    skill_id_required: null,
    respect_required: 400,
    link: "https://13floorgame.ru/images/works/admin.png",
  },
  {
    work_id: 5,
    name: {
      ru: "Менеджер по продажам",
      en: "Sales Manager"
    },
    requiredLevel: 5,
    coins_price: 1,
    coins_in_hour: 300,
    energy_cost_in_hour: 800,
    mood_cost_in_hour: 40,
    hungry_cost_in_hour: 65,
    skill_id_required: 4,
    respect_required: 550,
    link: "https://13floorgame.ru/images/works/salesManager.png",
  },
  {
    work_id: 6,
    name: {
      ru: "Менеджер по закупкам",
      en: "Purchasing Manager"
    },
    requiredLevel: 6,
    coins_price: 1,
    coins_in_hour: 350,
    energy_cost_in_hour: 950,
    mood_cost_in_hour: 45,
    hungry_cost_in_hour: 70,
    skill_id_required: null,
    respect_required: 700,
    link: "https://13floorgame.ru/images/works/purchasingManager.png",
  },
  {
    work_id: 7,
    name: {
      ru: "Маркетолог",
      en: "Marketer"
    },
    requiredLevel: 7,
    coins_price: 1,
    coins_in_hour: 400,
    energy_cost_in_hour: 1200,
    mood_cost_in_hour: 47,
    hungry_cost_in_hour: 72,
    skill_id_required: 5,
    respect_required: 900,
    link: "https://13floorgame.ru/images/works/marketer.png",
  },
  {
    work_id: 8,
    name: {
      ru: "HR",
      en: "HR"
    },
    requiredLevel: 8,
    coins_price: 1,
    coins_in_hour: 420,
    energy_cost_in_hour: 1500,
    mood_cost_in_hour: 49,
    hungry_cost_in_hour: 74,
    skill_id_required: 6,
    respect_required: 1000,
    link: "https://13floorgame.ru/images/works/hr.png",
  },
  {
    work_id: 9,
    name: {
      ru: "Менеджер проекта",
      en: "Project Manager"
    },
    requiredLevel: 9,
    coins_price: 1,
    coins_in_hour: 480,
    energy_cost_in_hour: 1800,
    mood_cost_in_hour: 51,
    hungry_cost_in_hour: 76,
    skill_id_required: null,
    respect_required: 1200,
    link: "https://13floorgame.ru/images/works/productManager.png",
  },
  {
    work_id: 10,
    name: {
      ru: "Тимлид",
      en: "Team Lead"
    },
    requiredLevel: 10,
    coins_price: 1,
    coins_in_hour: 540,
    energy_cost_in_hour: 2000,
    mood_cost_in_hour: 55,
    hungry_cost_in_hour: 80,
    skill_id_required: 8,
    respect_required: 1700,
    link: "https://13floorgame.ru/images/works/teamLid.png",
  },
  {
    work_id: 11,
    name: {
      ru: "Зам директора",
      en: "Deputy Director"
    },
    requiredLevel: 11,
    coins_price: 1,
    coins_in_hour: 600,
    energy_cost_in_hour: 2200,
    mood_cost_in_hour: 55,
    hungry_cost_in_hour: 80,
    skill_id_required: 9,
    respect_required: 2500,
    link: "https://13floorgame.ru/images/works/deputyDirector.png",
  },
  {
    work_id: 12,
    name: {
      ru: "Директор",
      en: "Director"
    },
    requiredLevel: 12,
    coins_price: 1,
    coins_in_hour: 660,
    energy_cost_in_hour: 2600,
    mood_cost_in_hour: 58,
    hungry_cost_in_hour: 82,
    skill_id_required: null,
    respect_required: 3000,
    link: "https://13floorgame.ru/images/works/director.png",
  },
  {
    work_id: 13,
    name: {
      ru: "Партнер",
      en: "Partner"
    },
    requiredLevel: 13,
    coins_price: 1,
    coins_in_hour: 720,
    energy_cost_in_hour: 2800,
    mood_cost_in_hour: 60,
    hungry_cost_in_hour: 85,
    skill_id_required: 10,
    respect_required: 4000,
    link: "https://13floorgame.ru/images/works/partner.png",
  },
  {
    work_id: 14,
    name: {
      ru: "CEO",
      en: "CEO"
    },
    requiredLevel: 14,
    coins_price: 1,
    coins_in_hour: 780,
    energy_cost_in_hour: 3500,
    mood_cost_in_hour: 63,
    hungry_cost_in_hour: 90,
    skill_id_required: 11,
    respect_required: 5000,
    link: "https://13floorgame.ru/images/works/seo.png",
  },
  {
    work_id: 15,
    name: {
      ru: "Миллионер",
      en: "Millionaire"
    },
    requiredLevel: 15,
    coins_price: 1,
    coins_in_hour: 800,
    energy_cost_in_hour: 3800,
    mood_cost_in_hour: 70,
    hungry_cost_in_hour: 95,
    skill_id_required: null,
    respect_required: 7500,
    link: "https://13floorgame.ru/images/works/millionaire.png",
  },
]