export default [
  {
    work_id: 1,
    name: "Курьер",
    coins_price: 20,
    coins_in_hour: 60,
    energy_cost_in_hour: 50,
    mood_cost_in_hour: 0.5,
    hungry_cost_in_hour: 1.25,
    skill_id_required: null,
    respect_required: 100,
    link: "https://13floorgame.ru/images/works/courier.png",
  },
  {
    work_id: 2,
    name: "Официант",
    coins_price: 150,
    coins_in_hour: 120,
    energy_cost_in_hour: 120,
    mood_cost_in_hour: 1,
    hungry_cost_in_hour: 2.5,
    skill_id_required: 1,
    respect_required: 150,
    link: "https://13floorgame.ru/images/works/waiter.png",
  },
  {
    work_id: 3,
    name: "Офис-менеджер",
    coins_price: 200,
    coins_in_hour: 180,
    energy_cost_in_hour: 180,
    mood_cost_in_hour: 2,
    hungry_cost_in_hour: 3.75,
    skill_id_required: 3,
    respect_required: 200,
    link: "https://13floorgame.ru/images/works/officeManager.png",
  },
  {
    work_id: 4,
    name: "Администратор",
    coins_price: 400,
    coins_in_hour: 240,
    energy_cost_in_hour: 240,
    mood_cost_in_hour: 4,
    hungry_cost_in_hour: 5,
    skill_id_required: null,
    respect_required: 400,
    link: "https://13floorgame.ru/images/works/admin.png",
  },
  {
    work_id: 5,
    name: "Менеджер по продажам",
    coins_price: 550,
    coins_in_hour: 300,
    energy_cost_in_hour: 300,
    mood_cost_in_hour: 3.5,
    hungry_cost_in_hour: 6,
    skill_id_required: 4,
    respect_required: 550,
    link: "https://13floorgame.ru/images/works/salesManager.png",
  },
  {
    work_id: 6,
    name: "Менеджер по закупкам",
    coins_price: 700,
    coins_in_hour: 350,
    energy_cost_in_hour: 350,
    mood_cost_in_hour: 4,
    hungry_cost_in_hour: 7,
    skill_id_required: null,
    respect_required: 700,
    link: "https://13floorgame.ru/images/works/purchasingManager.png",
  },
  {
    work_id: 7,
    name: "Маркетолог",
    coins_price: 900,
    coins_in_hour: 400,
    energy_cost_in_hour: 400,
    mood_cost_in_hour: 4.5,
    hungry_cost_in_hour: 8,
    skill_id_required: 5,
    respect_required: 900,
    link: "https://13floorgame.ru/images/works/marketer.png",
  },
  {
    work_id: 8,
    name: "HR",
    coins_price: 1000,
    coins_in_hour: 420,
    energy_cost_in_hour: 420,
    mood_cost_in_hour: 5,
    hungry_cost_in_hour: 8.25,
    skill_id_required: 6,
    respect_required: 1000,
    link: "https://13floorgame.ru/images/works/hr.png",
  },
  {
    work_id: 9,
    name: "Менеджер проекта",
    coins_price: 1200,
    coins_in_hour: 480,
    energy_cost_in_hour: 480,
    mood_cost_in_hour: 5.25,
    hungry_cost_in_hour: 8.5,
    skill_id_required: null,
    respect_required: 1200,
    link: "https://13floorgame.ru/images/works/productManager.png",
  },
  {
    work_id: 10,
    name: "Тимлид",
    coins_price: 1700,
    coins_in_hour: 540,
    energy_cost_in_hour: 540,
    mood_cost_in_hour: 5.5,
    hungry_cost_in_hour: 9,
    skill_id_required: 8,
    respect_required: 1700,
    link: "https://13floorgame.ru/images/works/teamLid.png",
  },
  {
    work_id: 11,
    name: "Зам директора",
    coins_price: 2500,
    coins_in_hour: 600,
    energy_cost_in_hour: 600,
    mood_cost_in_hour: 5.75,
    hungry_cost_in_hour: 9.25,
    skill_id_required: 9,
    respect_required: 2500,
    link: "https://13floorgame.ru/images/works/deputyDirector.png",
  },
  {
    work_id: 12,
    name: "Директор",
    coins_price: 3000,
    coins_in_hour: 660,
    energy_cost_in_hour: 660,
    mood_cost_in_hour: 6.25,
    hungry_cost_in_hour: 9.5,
    skill_id_required: null,
    respect_required: 3000,
    link: "https://13floorgame.ru/images/works/director.png",
  },
  {
    work_id: 13,
    name: "Партнер",
    coins_price: 4000,
    coins_in_hour: 720,
    energy_cost_in_hour: 720,
    mood_cost_in_hour: 6.5,
    hungry_cost_in_hour: 10,
    skill_id_required: 10,
    respect_required: 4000,
    link: "https://13floorgame.ru/images/works/partner.png",
  },
  {
    work_id: 14,
    name: "CEO",
    coins_price: 5000,
    coins_in_hour: 780,
    energy_cost_in_hour: 780,
    mood_cost_in_hour: 6.75,
    hungry_cost_in_hour: 11,
    skill_id_required: 11,
    respect_required: 5000,
    link: "https://13floorgame.ru/images/works/seo.png",
  },
  {
    work_id: 15,
    name: "Миллионер",
    coins_price: 7500,
    coins_in_hour: 800,
    energy_cost_in_hour: 800,
    mood_cost_in_hour: 7,
    hungry_cost_in_hour: 12,
    skill_id_required: null,
    respect_required: 7500,
    link: "https://13floorgame.ru/images/works/millionaire.png",
  },
]
