export default [
  {
    work_id: 1,
    name: {
      ru: "Уборщик",
      en: "Janitor"
    },
    requiredLevel: 1,
    coins_price: 1,
    coins_in_hour: 60,
    energy_cost_in_hour: 100,
    mood_cost_in_hour: 20,
    hungry_cost_in_hour: 28,
    skill_id_required: null,
    respect_required: 0,
    link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/icons%2F%D0%A3%D0%B1%D0%BE%D1%80%D1%89%D0%B8%D0%BA.png",
  },
  {
    work_id: 2,
    name: {
      ru: "Курьер",
      en: "Courier"
    },
    requiredLevel: 1,
    coins_price: 1,
    coins_in_hour: 120,
    energy_cost_in_hour: 150,
    mood_cost_in_hour: 22,
    hungry_cost_in_hour: 30,
    skill_id_required: null,
    respect_required: 50,
    link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/icons%2F%D0%BA%D1%83%D1%80%D1%8C%D0%B5%D1%80.png",
  },
  {
    work_id: 3,
    name: {
      ru: "Мойщик тарелок",
      en: "Plate washer"
    },
    requiredLevel: 2,
    coins_price: 5,
    coins_in_hour: 180,
    energy_cost_in_hour: 200,
    mood_cost_in_hour: 24,
    hungry_cost_in_hour: 32,
    skill_id_required: 1,
    respect_required: 70,
    link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/icons%2F%D0%BC%D0%BE%D0%B9%D1%89%D0%B8%D0%BA-%D1%82%D0%B0%D1%80%D0%B5%D0%BB%D0%BE%D0%BA.png",
  },
  {
    work_id: 4,
    name: {
      ru: "Официант",
      en: "Waiter"
    },
    requiredLevel: 2,
    coins_price: 5,
    coins_in_hour: 240,
    energy_cost_in_hour: 300,
    mood_cost_in_hour: 26,
    hungry_cost_in_hour: 34,
    skill_id_required: 1,
    respect_required: 100,
    link: "https://13floorgame.ru/images/works/waiter.png",
  },
  {
    work_id: 5,
    name: {
      ru: "Администратор",
      en: "Manager"
    },
    requiredLevel: 2,
    coins_price: 5,
    coins_in_hour: 300,
    energy_cost_in_hour: 500,
    mood_cost_in_hour: 28,
    hungry_cost_in_hour: 36,
    skill_id_required: 1,
    respect_required: 150,
    link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/icons%2F%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80-%D1%80%D0%B5%D1%81%D1%82%D0%B8%D0%BA%D0%B0.png",
  },
  {
    work_id: 6,
    name: {
      ru: "Секретарь",
      en: "Secretary"
    },
    requiredLevel: 3,
    coins_price: 30,
    coins_in_hour: 360,
    energy_cost_in_hour: 600,
    mood_cost_in_hour: 30,
    hungry_cost_in_hour: 38,
    skill_id_required: 3,
    respect_required: 200,
    link: "https://13floorgame.ru/images/works/officeManager.png",
  },
  {
    work_id: 7,
    name: {
      ru: "Офис-менеджер",
      en: "Office Manager"
    },
    requiredLevel: 4,
    coins_price: 100,
    coins_in_hour: 420,
    energy_cost_in_hour: 650,
    mood_cost_in_hour: 34,
    hungry_cost_in_hour: 40,
    skill_id_required: null,
    respect_required: 250,
    link: "https://13floorgame.ru/images/works/admin.png",
  },
  {
    work_id: 8,
    name: {
      ru: "Менеджер по продажам",
      en: "Sales Manager"
    },
    requiredLevel: 5,
    coins_price: 300,
    coins_in_hour: 480,
    energy_cost_in_hour: 900,
    mood_cost_in_hour: 38,
    hungry_cost_in_hour: 44,
    skill_id_required: 4,
    respect_required: 300,
    link: "https://13floorgame.ru/images/works/salesManager.png",
  },
  {
    work_id: 9,
    name: {
      ru: "Менеджер по закупкам",
      en: "Purchasing Manager"
    },
    requiredLevel: 6,
    coins_price: 700,
    coins_in_hour: 540,
    energy_cost_in_hour: 1000,
    mood_cost_in_hour: 42,
    hungry_cost_in_hour: 48,
    skill_id_required: null,
    respect_required: 400,
    link: "https://13floorgame.ru/images/works/purchasingManager.png",
  },
  {
    work_id: 10,
    name: {
      ru: "Копирайтер",
      en: "Copywriter"
    },
    requiredLevel: 7,
    coins_price: 900,
    coins_in_hour: 600,
    energy_cost_in_hour: 1100,
    mood_cost_in_hour: 46,
    hungry_cost_in_hour: 52,
    skill_id_required: 5,
    respect_required: 500,
    link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/icons%2F%D0%9A%D0%BE%D0%BF%D0%B8%D1%80%D0%B0%D0%B9%D1%82%D0%B5%D1%80.png",
  },
  {
    work_id: 11,
    name: {
      ru: "Маркетолог",
      en: "Marketer"
    },
    requiredLevel: 7,
    coins_price: 900,
    coins_in_hour: 660,
    energy_cost_in_hour: 1200,
    mood_cost_in_hour: 50,
    hungry_cost_in_hour: 56,
    skill_id_required: 5,
    respect_required: 600,
    link: "https://13floorgame.ru/images/works/marketer.png",
  },
  {
    work_id: 12,
    name: {
      ru: "Бренд-менеджер",
      en: "Brand Manager"
    },
    requiredLevel: 8,
    coins_price: 1000,
    coins_in_hour: 720,
    energy_cost_in_hour: 1300,
    mood_cost_in_hour: 54,
    hungry_cost_in_hour: 60,
    skill_id_required: 6,
    respect_required: 750,
    link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/icons%2F%D0%B1%D1%80%D0%B5%D0%BD%D0%B4-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80.png",
  },
  {
    work_id: 13,
    name: {
      ru: "HR",
      en: "HR"
    },
    requiredLevel: 8,
    coins_price: 1000,
    coins_in_hour: 780,
    energy_cost_in_hour: 1400,
    mood_cost_in_hour: 58,
    hungry_cost_in_hour: 64,
    skill_id_required: 6,
    respect_required: 900,
    link: "https://13floorgame.ru/images/works/hr.png",
  },
  {
    work_id: 14,
    name: {
      ru: "Менеджер проекта",
      en: "Project Manager"
    },
    requiredLevel: 9,
    coins_price: 1200,
    coins_in_hour: 840,
    energy_cost_in_hour: 1500,
    mood_cost_in_hour: 62,
    hungry_cost_in_hour: 68,
    skill_id_required: null,
    respect_required: 1050,
    link: "https://13floorgame.ru/images/works/productManager.png",
  },
  {
    work_id: 15,
    name: {
      ru: "Тимлид",
      en: "Team Lead"
    },
    requiredLevel: 10,
    coins_price: 1300,
    coins_in_hour: 900,
    energy_cost_in_hour: 1600,
    mood_cost_in_hour: 66,
    hungry_cost_in_hour: 72,
    skill_id_required: 8,
    respect_required: 1200,
    link: "https://13floorgame.ru/images/works/teamLid.png",
  },
  {
    work_id: 16,
    name: {
      ru: "Зам директора",
      en: "Deputy Director"
    },
    requiredLevel: 11,
    coins_price: 1800,
    coins_in_hour: 960,
    energy_cost_in_hour: 1700,
    mood_cost_in_hour: 70,
    hungry_cost_in_hour: 76,
    skill_id_required: 9,
    respect_required: 1350,
    link: "https://13floorgame.ru/images/works/deputyDirector.png",
  },
  {
    work_id: 17,
    name: {
      ru: "Директор",
      en: "Executive"
    },
    requiredLevel: 12,
    coins_price: 2500,
    coins_in_hour: 1020,
    energy_cost_in_hour: 1800,
    mood_cost_in_hour: 74,
    hungry_cost_in_hour: 80,
    skill_id_required: null,
    respect_required: 1500,
    link: "https://13floorgame.ru/images/works/director.png",
  },
  {
    work_id: 18,
    name: {
      ru: "Партнер",
      en: "Partner"
    },
    requiredLevel: 13,
    coins_price: 1,
    coins_in_hour: 1080,
    energy_cost_in_hour: 1900,
    mood_cost_in_hour: 78,
    hungry_cost_in_hour: 84,
    skill_id_required: 10,
    respect_required: 1650,
    link: "https://13floorgame.ru/images/works/partner.png",
  },
  {
    work_id: 19,
    name: {
      ru: "CEO",
      en: "CEO"
    },
    requiredLevel: 14,
    coins_price: 5000,
    coins_in_hour: 1140,
    energy_cost_in_hour: 2000,
    mood_cost_in_hour: 82,
    hungry_cost_in_hour: 88,
    skill_id_required: 11,
    respect_required: 1800,
    link: "https://13floorgame.ru/images/works/seo.png",
  },
  {
    work_id: 20,
    name: {
      ru: "Миллионер",
      en: "Millionaire"
    },
    requiredLevel: 15,
    coins_price: 10000,
    coins_in_hour: 1200,
    energy_cost_in_hour: 3000,
    mood_cost_in_hour: 86,
    hungry_cost_in_hour: 92,
    skill_id_required: null,
    respect_required: 2500,
    link: "https://13floorgame.ru/images/works/millionaire.png",
  },
]