export default [
  {
    name_ru: "Новичок в обучении",
    name_en: "Training Rookie",
    descr_ru: "Завершите обучение одного навыка и станьте немного умнее.",
    descr_en: "Complete training for one skill and become a little smarter.",
    reward: null,
    link: "#",
    level: 1,
    type: "training_rookie",
  },
  {
    name_ru: "Займись спортом",
    name_en: "Get Active",
    descr_ru: "Проведите тренировку и почувствуйте прилив позитивных эмоций!",
    descr_en: "Complete a workout and feel the rush of positive emotions!",
    reward: 0,
    link: "#",
    level: 1,
    type: "get_active",
  },
  {
    name_ru: "Пригласи друга",
    name_en: "Invite a Friend",
    descr_ru:
      "Пригласите друга и откройте игровой центр. Получайте дополнительные монеты каждый час.",
    descr_en:
      "Invite a friend and open a game center. Earn extra coins every hour.",
    reward: null,
    link: "#",
    level: 1,
    type: "invite_friend",
  },
  {
    name_ru: "Пригласи 5 друзей",
    name_en: "Invite 5 Friends",
    descr_ru:
      "Получите ретро-консоль, которая помогает дольше оставаться счастливым.",
    descr_en:
      "Invite 5 friends to get a retro console that helps maintain happiness.",
    reward: "Ретро-консоль",
    link: "#",
    level: 1,
    type: "invite_five_friends",
  },
  {
    name_ru: "Достигните 2 уровня",
    name_en: "Reach Level 2",
    descr_ru: "Сделайте первый шаг на пути к успеху.",
    descr_en: "Take the first step on your way to success.",
    reward: "Опыт",
    link: "#",
    level: 2,
    type: "reach_level_2",
  },
  {
    name_ru: "Мотивирующий подкаст",
    name_en: "Motivational Podcast",
    descr_ru: "Послушайте подкаст, который вдохновит вас на новые достижения.",
    descr_en: "Listen to a podcast that will inspire you to achieve more.",
    reward: "Вдохновение",
    link: "#",
    level: 2,
    type: "motivational_podcast",
  },
  {
    name_ru: "Спортивная одежда",
    name_en: "Sportswear",
    descr_ru: "Приобретите спортивную одежду для комфорта и мотивации.",
    descr_en: "Purchase sportswear for comfort and motivation.",
    reward: "Одежда",
    link: "#",
    level: 2,
    type: "buy_sportswear",
  },
  {
    name_ru: "Получи новую работу",
    name_en: "Get a New Job",
    descr_ru: "Устройтесь на работу официантом и начните свою карьеру!",
    descr_en: "Get a job as a waiter and start your career!",
    reward: "Работа",
    link: "#",
    level: 2,
    type: "get_new_job",
  },
  {
    name_ru: "Пригласи 10 друзей",
    name_en: "Invite 10 Friends",
    descr_ru: "Улучшите игровой центр до 3 уровня, пригласив 10 друзей.",
    descr_en: "Upgrade your game center to level 3 by inviting 10 friends.",
    reward: "Улучшение игрового центра",
    link: "#",
    level: 2,
    type: "invite_ten_friends",
  },
  {
    name_ru: "Новые упражнения",
    name_en: "New Exercises",
    descr_ru: "Освойте новые упражнения для разнообразия тренировок.",
    descr_en: "Learn new exercises to diversify your workouts.",
    reward: "Знания о упражнениях",
    link: "#",
    level: 2,
    type: "learn_new_exercises",
  },
  {
    name_ru: "Офисные программы",
    name_en: "Office Software",
    descr_ru: "Изучите офисные программы для повышения продуктивности.",
    descr_en: "Learn office software to increase productivity.",
    reward: "Навыки работы с ПО",
    link: "#",
    level: 2,
    type: "learn_office_software",
  },
  {
    name_ru: "Ранний пташка",
    name_en: "Early Bird",
    descr_ru: "Проведите 8 часов на работе за один день.",
    descr_en: "Spend 8 hours working in one day.",
    reward: "Опыт работы",
    link: "#",
    level: 3,
    type: "early_bird",
  },
  {
    name_ru: "День спорта",
    name_en: "Sports Day",
    descr_ru: "Проведите 2 часа подряд в тренировках.",
    descr_en: "Spend 2 consecutive hours working out.",
    reward: "Физическая форма",
    link: "#",
    level: 3,
    type: "sports_day",
  },
  {
    name_ru: "Персональный тренер",
    name_en: "Personal Trainer",
    descr_ru:
      "Закажите первую персональную тренировку и сделайте шаг к совершенству.",
    descr_en:
      "Book your first personal training session and take a step towards perfection.",
    reward: "Персональная тренировка",
    link: "#",
    level: 3,
    type: "personal_trainer",
  },
  {
    name_ru: "Первый массаж",
    name_en: "The First Massage",
    descr_ru: "Опробуйте расслабляющий массаж.",
    descr_en: "Try a relaxing massage.",
    reward: "Расслабление",
    link: "#",
    level: 3,
    type: "first_massage",
  },
  {
    name_ru: "Любитель энергетиков",
    name_en: "Energy Drink Enthusiast",
    descr_ru:
      "Совершите первую покупку банки энергетика и ощутите прилив энергии!",
    descr_en:
      "Make your first energy drink purchase and feel the energy boost!",
    reward: "Энергия",
    link: "#",
    level: 3,
    type: "energy_drink_enthusiast",
  },
  {
    name_ru: "Станьте офис-менеджером",
    name_en: "Become an Office Manager",
    descr_ru: "Работа в офисе – новый этап вашей карьеры.",
    descr_en: "Office work – a new stage in your career.",
    reward: "Карьера в офисе",
    link: "#",
    level: 3,
    type: "become_office_manager",
  },
  {
    name_ru: "Любитель знаний",
    name_en: "Knowledge Lover",
    descr_ru:
      "Купите первое ускорение обучения на 20% и откройте путь к быстрому прогрессу.",
    descr_en:
      "Buy your first 20% learning boost and unlock the path to faster progress.",
    reward: "Ускорение обучения",
    link: "#",
    level: 3,
    type: "knowledge_lover",
  },
  {
    name_ru: "1я Инвестиция",
    name_en: "First Investment",
    descr_ru:
      "Инвестируйте деньги в первый бизнес и сделайте шаг к финансовой свободе.",
    descr_en:
      "Invest in your first business and take a step toward financial freedom.",
    reward: "",
    link: "",
    level: 4,
    type: "first_investment",
  },
  {
    name_ru: "Мастер рабочего времени",
    name_en: "Master of Work Time",
    descr_ru: "Отработайте 40 часов за неделю.",
    descr_en: "Work 40 hours in a week.",
    reward: "",
    link: "",
    level: 4,
    type: "master_of_work_time",
  },
  {
    name_ru: "Эксперт по массажу",
    name_en: "Massage Expert",
    descr_ru: "Закажите 5 массажей и достигните уровня гармонии.",
    descr_en: "Order 5 massages and achieve a state of harmony.",
    reward: "",
    link: "",
    level: 4,
    type: "massage_expert",
  },
  {
    name_ru: "Станьте администратором",
    name_en: "Become an Administrator",
    descr_ru:
      "Теперь вы управляете небольшими процессами и руководите командой.",
    descr_en: "Now you're managing small processes and leading a team.",
    reward: "",
    link: "",
    level: 4,
    type: "become_an_administrator",
  },
  {
    name_ru: "Онлайн обучение",
    name_en: "Online Education",
    descr_ru: "Пройдите онлайн-курс и узнайте что-то новое.",
    descr_en: "Take an online course and learn something new.",
    reward: "",
    link: "",
    level: 4,
    type: "online_education",
  },
  {
    name_ru: "Трудоголик",
    name_en: "Workaholic",
    descr_ru: "Проработайте 200 часов суммарно.",
    descr_en: "Work a total of 200 hours.",
    reward: "",
    link: "",
    level: 5,
    type: "workaholic",
  },
  {
    name_ru: "Станьте менеджером по продажам",
    name_en: "Become a Sales Manager",
    descr_ru: "Узнайте все секреты успешных сделок.",
    descr_en: "Learn all the secrets of successful deals.",
    reward: "",
    link: "",
    level: 5,
    type: "become_a_sales_manager",
  },
  {
    name_ru: "Тест-драйв помощника",
    name_en: "Assistant Test Drive",
    descr_ru: "Найдите робота-помощника на 12 часов и узнайте его возможности.",
    descr_en:
      "Hire a robot assistant for 12 hours and explore its capabilities.",
    reward: "",
    link: "",
    level: 5,
    type: "assistant_test_drive",
  },
  {
    name_ru: "Достигните 5 уровня",
    name_en: "Reach Level 5",
    descr_ru: "Ваши усилия не прошли даром – вы поднялись до 5 уровня!",
    descr_en: "Your efforts paid off – you reached level 5!",
    reward: "",
    link: "",
    level: 5,
    type: "reach_level_5",
  },
  {
    name_ru: "Стремящийся к знаниям",
    name_en: "Knowledge Seeker",
    descr_ru: "Купите 5 ускорений на 20% и улучшите свои навыки ещё быстрее.",
    descr_en: "Buy 5 20% learning boosts and improve your skills even faster.",
    reward: "",
    link: "",
    level: 5,
    type: "knowledge_seeker",
  },
  {
    name_ru: "Тренер по здоровью",
    name_en: "Health Coach",
    descr_ru: "Закажите 5 консультаций с тренером по здоровью и укрепите тело.",
    descr_en:
      "Book 5 consultations with a health coach and strengthen your body.",
    reward: "",
    link: "",
    level: 6,
    type: "health_coach",
  },
  {
    name_ru: "Станьте менеджером по закупкам",
    name_en: "Become a Purchasing Manager",
    descr_ru: "Организуйте поставки и оптимизируйте процессы.",
    descr_en: "Organize supplies and optimize processes.",
    reward: "",
    link: "",
    level: 6,
    type: "become_a_purchasing_manager",
  },
  {
    name_ru: "Бессмертный карьерист",
    name_en: "Immortal Careerist",
    descr_ru: "Превратите 1000 часов труда в успех!",
    descr_en: "Turn 1000 hours of work into success!",
    reward: "",
    link: "",
    level: 6,
    type: "immortal_careerist",
  },
  {
    name_ru: "Доверенный ассистент",
    name_en: "Trusted Assistant",
    descr_ru:
      "Найдите робота 5 раз и почувствуйте, как задачи решаются быстрее.",
    descr_en: "Hire a robot 5 times and feel how tasks get solved faster.",
    reward: "",
    link: "",
    level: 6,
    type: "trusted_assistant",
  },
  {
    name_ru: "Завсегдатай энергетических коктейлей",
    name_en: "Energy Drink Regular",
    descr_ru:
      "Купите 5 энергетиков и докажите, что вы знаете толк в поддержке сил.",
    descr_en:
      "Buy 5 energy drinks and prove you're a master of staying energized.",
    reward: "",
    link: "",
    level: 6,
    type: "energy_drink_regular",
  },
  {
    // Уровень 7
    name_ru: "Мастер релакса",
    name_en: "Master of Relaxation",
    descr_ru: "Проведите 50 часов в состоянии отдыха.",
    descr_en: "Spend 50 hours in a state of sleep.",
    reward: "",
    link: "",
    level: 7,
    type: "master_of_relaxation",
  },
  {
    name_ru: "Золотой стажер",
    name_en: "Golden Intern",
    descr_ru: "Проведите 500 часов на различных работах.",
    descr_en: "Spend 500 hours on various jobs.",
    reward: "",
    link: "",
    level: 7,
    type: "golden_intern",
  },
  {
    name_ru: "Станьте маркетологом",
    name_en: "Become a Marketer",
    descr_ru: "Проявите свои таланты в продвижении и рекламе.",
    descr_en: "Showcase your talents in promotion and advertising.",
    reward: "",
    link: "",
    level: 7,
    type: "become_a_marketer",
  },
  {
    name_ru: "Тренинг по рекламе",
    name_en: "Advertising Training",
    descr_ru:
      "Примите участие в тренинге и узнайте секреты успешного продвижения.",
    descr_en:
      "Take part in training and learn the secrets of successful promotion.",
    reward: "",
    link: "",
    level: 7,
    type: "advertising_training",
  },
  {
    name_ru: "Посол релакса",
    name_en: "Ambassador of Relaxation",
    descr_ru: "Пройдите 10 массажей и станьте знатоком покоя и восстановления.",
    descr_en:
      "Complete 10 massages and become an expert in peace and recovery.",
    reward: "",
    link: "",
    level: 7,
    type: "ambassador_of_relaxation",
  },
  {
    name_ru: "Фанат тонуса",
    name_en: "Tone Enthusiast",
    descr_ru:
      "Купите 10 банок энергетиков, чтобы показать свою приверженность бодрости.",
    descr_en:
      "Buy 10 cans of energy drinks to show your commitment to staying energized.",
    reward: "",
    link: "",
    level: 7,
    type: "tone_enthusiast",
  },
  {
    name_ru: "Курсы подбора персонала",
    name_en: "HR Training",
    descr_ru: "Освойте навыки HR и эффективного управления кадрами.",
    descr_en: "Master HR skills and effective personnel management.",
    reward: "",
    link: "",
    level: 7,
    type: "hr_training",
  },
  {
    name_ru: "Гуру здоровья",
    name_en: "Health Guru",
    descr_ru:
      "Пройдите 10 консультаций и станьте гуру в области здоровья и фитнеса.",
    descr_en: "Complete 10 consultations and become a health and fitness guru.",
    reward: "",
    link: "",
    level: 7,
    type: "health_guru",
  },
  {
    name_ru: "Ценитель технологий",
    name_en: "Tech Enthusiast",
    descr_ru: "Найдите робота 10 раз и покажите, что вы в ногу с прогрессом.",
    descr_en:
      "Hire a robot 10 times and show that you're keeping up with progress.",
    reward: "",
    link: "",
    level: 7,
    type: "tech_enthusiast",
  },
  {
    name_ru: "Хозяин машин",
    name_en: "Master of Machines",
    descr_ru: "Найдите робота 15 раз и станьте мастером автоматизации.",
    descr_en: "Hire a robot 15 times and become a master of automation.",
    reward: "",
    link: "",
    level: 7,
    type: "master_of_machines",
  },
  // Уровень 8
  {
    name_ru: "Станьте HR-менеджером",
    name_en: "Become an HR Manager",
    descr_ru: "Работайте с людьми и помогайте компании расти.",
    descr_en: "Work with people and help the company grow.",
    reward: "",
    link: "",
    level: 8,
    type: "become_an_hr_manager",
  },
  {
    name_ru: "Эрудит на максималках",
    name_en: "Maximum Scholar",
    descr_ru:
      "Купите 10 ускорений и станьте настоящим мастером учебного процесса.",
    descr_en: "Buy 10 boosts and become a true master of the learning process.",
    reward: "",
    link: "",
    level: 8,
    type: "maximum_scholar",
  },
  {
    name_ru: "Энциклопедия бодибилдинга",
    name_en: "Encyclopedia of Bodybuilding",
    descr_ru:
      "Изучите энциклопедию, чтобы углубить знания о тренировках и питании.",
    descr_en:
      "Study the encyclopedia to deepen your knowledge of training and nutrition.",
    reward: "",
    link: "",
    level: 8,
    type: "encyclopedia_of_bodybuilding",
  },
  {
    name_ru: "Статья о здоровом сне",
    name_en: "Article on Healthy Sleep",
    descr_ru:
      "Прочитайте статью о важности сна для здоровья и работоспособности.",
    descr_en:
      "Read an article about the importance of sleep for health and productivity.",
    reward: "",
    link: "",
    level: 8,
    type: "article_on_healthy_sleep",
  },
  {
    name_ru: "Гений времени",
    name_en: "Genius of Time",
    descr_ru:
      "Купите 15 ускорений и оптимизируйте процесс обучения до совершенства.",
    descr_en: "Buy 15 boosts and optimize the learning process to perfection.",
    reward: "",
    link: "",
    level: 8,
    type: "genius_of_time",
  },

  // Уровень 9
  {
    name_ru: "Станьте менеджером проекта",
    name_en: "Become a Project Manager",
    descr_ru: "Планируйте и управляйте крупными задачами.",
    descr_en: "Plan and manage major tasks.",
    reward: "",
    link: "",
    level: 9,
    type: "become_a_project_manager",
  },
  {
    name_ru: "Мастер расслабления",
    name_en: "Master of Relaxation",
    descr_ru: "Закажите 15 массажей и станьте символом баланса и релаксации.",
    descr_en:
      "Complete 15 massages and become a symbol of balance and relaxation.",
    reward: "",
    link: "",
    level: 9,
    type: "master_of_relaxation",
  },
  {
    name_ru: "Энтузиаст бодрости",
    name_en: "Energy Boost Enthusiast",
    descr_ru:
      "Совершите 15 покупок тонизирующих напитков и станьте мастером восстановления энергии.",
    descr_en:
      "Make 15 energy drink purchases and become a master of energy restoration.",
    reward: "",
    link: "",
    level: 9,
    type: "energy_boost_enthusiast",
  },
  {
    name_ru: "Школа менеджмента",
    name_en: "Management School",
    descr_ru: "Посетите школу менеджмента, чтобы освоить навыки лидерства.",
    descr_en: "Visit a management school to master leadership skills.",
    reward: "",
    link: "",
    level: 9,
    type: "management_school",
  },

  // Уровень 10
  {
    name_ru: "Достигните 10 уровня",
    name_en: "Reach Level 10",
    descr_ru: "Вы доказали свою стойкость, достигнув 10 уровня.",
    descr_en: "You've proven your perseverance by reaching level 10.",
    reward: "",
    link: "",
    level: 10,
    type: "reach_level_10",
  },
  {
    name_ru: "Хранитель спокойствия",
    name_en: "Keeper of Calmness",
    descr_ru: "Потратьте 200 часов на отдых.",
    descr_en: "Spend 200 hours on rest.",
    reward: "",
    link: "",
    level: 10,
    type: "keeper_of_calmness",
  },
  // Уровень 8
  {
    name_ru: "Станьте HR-менеджером",
    name_en: "Become an HR Manager",
    descr_ru: "Работайте с людьми и помогайте компании расти.",
    descr_en: "Work with people and help the company grow.",
    reward: "",
    link: "",
    level: 8,
    type: "become_an_hr_manager",
  },
  {
    name_ru: "Эрудит на максималках",
    name_en: "Maximum Scholar",
    descr_ru:
      "Купите 10 ускорений и станьте настоящим мастером учебного процесса.",
    descr_en: "Buy 10 boosts and become a true master of the learning process.",
    reward: "",
    link: "",
    level: 8,
    type: "maximum_scholar",
  },
  {
    name_ru: "Энциклопедия бодибилдинга",
    name_en: "Encyclopedia of Bodybuilding",
    descr_ru:
      "Изучите энциклопедию, чтобы углубить знания о тренировках и питании.",
    descr_en:
      "Study the encyclopedia to deepen your knowledge of training and nutrition.",
    reward: "",
    link: "",
    level: 8,
    type: "encyclopedia_of_bodybuilding",
  },
  {
    name_ru: "Статья о здоровом сне",
    name_en: "Article on Healthy Sleep",
    descr_ru:
      "Прочитайте статью о важности сна для здоровья и работоспособности.",
    descr_en:
      "Read an article about the importance of sleep for health and productivity.",
    reward: "",
    link: "",
    level: 8,
    type: "article_on_healthy_sleep",
  },
  {
    name_ru: "Гений времени",
    name_en: "Genius of Time",
    descr_ru:
      "Купите 15 ускорений и оптимизируйте процесс обучения до совершенства.",
    descr_en: "Buy 15 boosts and optimize the learning process to perfection.",
    reward: "",
    link: "",
    level: 8,
    type: "genius_of_time",
  },

  // Уровень 9
  {
    name_ru: "Станьте менеджером проекта",
    name_en: "Become a Project Manager",
    descr_ru: "Планируйте и управляйте крупными задачами.",
    descr_en: "Plan and manage major tasks.",
    reward: "",
    link: "",
    level: 9,
    type: "become_a_project_manager",
  },
  {
    name_ru: "Мастер расслабления",
    name_en: "Master of Relaxation",
    descr_ru: "Закажите 15 массажей и станьте символом баланса и релаксации.",
    descr_en:
      "Complete 15 massages and become a symbol of balance and relaxation.",
    reward: "",
    link: "",
    level: 9,
    type: "master_of_relaxation",
  },
  {
    name_ru: "Энтузиаст бодрости",
    name_en: "Energy Boost Enthusiast",
    descr_ru:
      "Совершите 15 покупок тонизирующих напитков и станьте мастером восстановления энергии.",
    descr_en:
      "Make 15 energy drink purchases and become a master of energy restoration.",
    reward: "",
    link: "",
    level: 9,
    type: "energy_boost_enthusiast",
  },
  {
    name_ru: "Школа менеджмента",
    name_en: "Management School",
    descr_ru: "Посетите школу менеджмента, чтобы освоить навыки лидерства.",
    descr_en: "Visit a management school to master leadership skills.",
    reward: "",
    link: "",
    level: 9,
    type: "management_school",
  },

  // Уровень 10
  {
    name_ru: "Достигните 10 уровня",
    name_en: "Reach Level 10",
    descr_ru: "Вы доказали свою стойкость, достигнув 10 уровня.",
    descr_en: "You've proven your perseverance by reaching level 10.",
    reward: "",
    link: "",
    level: 10,
    type: "reach_level_10",
  },
  {
    name_ru: "Хранитель спокойствия",
    name_en: "Keeper of Calmness",
    descr_ru: "Потратьте 200 часов на отдых.",
    descr_en: "Spend 200 hours on rest.",
    reward: "",
    link: "",
    level: 10,
    type: "keeper_of_calmness",
  },
  {
    name_ru: "Легендарный техномаг",
    name_en: "Legendary Techno Wizard",

    descr_ru:
      "Поддержите проект, наймя робота 50 раз, и закрепите за собой этот титул!",
    descr_en:
      "Support the project by hiring a robot 50 times and earn this title!",
    reward: "",
    link: "",
    level: 10,
    type: "legendary_techno_wizard",
  },
  {
    name_ru: "Легенда энергетиков",
    name_en: "Legend of Energy Drinks",
    descr_ru:
      "Поддержите проект, купив 50 энергетиков, и впишите свое имя в историю бодрости!",
    descr_en:
      "Support the project by buying 50 energy drinks and write your name in the history of energy.",
    reward: "",
    link: "",
    level: 10,
    type: "legend_of_energy_drinks",
  },
  {
    name_ru: "Станьте тимлидом",
    name_en: "Become a Team Lead",
    descr_ru: "Возглавьте свою команду и добейтесь успеха вместе.",
    descr_en: "Lead your team and achieve success together.",
    reward: "",
    link: "",
    level: 10,
    type: "become_a_team_lead",
  },
  {
    name_ru: "Бизнес-тренинг",
    name_en: "Business Training",
    descr_ru:
      "Пройдите тренинг, чтобы узнать, как эффективно развивать бизнес.",
    descr_en: "Take training to learn how to effectively grow a business.",
    reward: "",
    link: "",
    level: 10,
    type: "business_training",
  },
  {
    name_ru: "Человек-легенда",
    name_en: "Legend of Health",
    descr_ru:
      "Получите 50 консультаций по здоровью и приобретите статус настоящего эксперта!",
    descr_en:
      "Complete 50 health consultations and earn the status of a true expert!",
    reward: "",
    link: "",
    level: 10,
    type: "legend_of_health",
  },

  // Уровень 11
  {
    name_ru: "Марафонец",
    name_en: "Marathoner",
    descr_ru: "Проведите 200 часов на спортивных активностях.",
    descr_en: "Spend 200 hours on sports activities.",
    reward: "",
    link: "",
    level: 11,
    type: "marathoner",
  },
  {
    name_ru: "Архитектор знаний",
    name_en: "Architect of Knowledge",
    descr_ru:
      "Поддержите проект, купив 50 ускорений, и станьте символом скорости прогресса.",
    descr_en:
      "Support the project by buying 50 boosts and become a symbol of progress speed.",
    reward: "",
    link: "",
    level: 11,
    type: "architect_of_knowledge",
  },
  {
    name_ru: "Станьте замдиректором",
    name_en: "Become a Deputy Director",
    descr_ru: "Управляйте ключевыми процессами компании.",
    descr_en: "Manage key company processes.",
    reward: "",
    link: "",
    level: 11,
    type: "become_a_deputy_director",
  },

  // Уровень 12
  {
    name_ru: "Икона фитнеса",
    name_en: "Fitness Icon",
    descr_ru: "Суммарно тренируйтесь 500 часов.",
    descr_en: "Train a total of 500 hours.",
    reward: "",
    link: "",
    level: 12,
    type: "fitness_icon",
  },
  {
    name_ru: "Станьте директором",
    name_en: "Become a Director",
    descr_ru: "Теперь вы управляете всей организацией!",
    descr_en: "Now you're in charge of the entire organization!",
    reward: "",
    link: "",
    level: 12,
    type: "become_a_director",
  },
  {
    name_ru: "Тренинг по автоматизации",
    name_en: "Automation Training",
    descr_ru:
      "Узнайте, как автоматизировать процессы и повысить производительность.",
    descr_en: "Learn how to automate processes and increase productivity.",
    reward: "",
    link: "",
    level: 12,
    type: "automation_training",
  },

  // Уровень 13
  {
    name_ru: "Станьте партнером",
    name_en: "Become a Partner",
    descr_ru: "Войдите в долю компании и получите стратегический контроль.",
    descr_en: "Join the company’s equity and gain strategic control.",
    reward: "",
    link: "",
    level: 13,
    type: "become_a_partner",
  },
  {
    name_ru: "Экономическое образование",
    name_en: "Economic Education",
    descr_ru: "Изучите основы экономики, чтобы грамотно управлять финансами.",
    descr_en: "Learn the basics of economics to manage finances effectively.",
    reward: "",
    link: "",
    level: 13,
    type: "economic_education",
  },

  // Уровень 14
  {
    name_ru: "Станьте CEO",
    name_en: "Become CEO",
    descr_ru: "Займите место руководителя и ведите компанию к новым вершинам.",
    descr_en: "Take the CEO position and lead the company to new heights.",
    reward: "",
    link: "",
    level: 14,
    type: "become_ceo",
  },

  // Уровень 15
  {
    name_ru: "Все подождет",
    name_en: "Everything Can Wait",
    descr_ru: "Проведите 500 часов во сне.",
    descr_en: "Spend 500 hours sleeping.",
    reward: "",
    link: "",
    level: 15,
    type: "everything_can_wait",
  },
  {
    name_ru: "Достигните 15 уровня",
    name_en: "Reach Level 15",
    descr_ru: "Пройдите рубеж 15 уровня и станьте профессионалом своего дела.",
    descr_en: "Reach level 15 and become a professional in your field.",
    reward: "",
    link: "",
    level: 15,
    type: "reach_level_15",
  },
  {
    name_ru: "Станьте миллионером",
    name_en: "Become a Millionaire",
    descr_ru:
      "Вы достигли пика успеха – наслаждайтесь своей жизнью и богатством!",
    descr_en:
      "You've reached the peak of success – enjoy your life and wealth!",
    reward: "",
    link: "",
    level: 15,
    type: "become_a_millionaire",
  },
  {
    name_ru: "Легенда спокойствия",
    name_en: "Legend of Calmness",
    descr_ru: "Совершите 50 заказов и обретите статус вдохновителя гармонии!",
    descr_en: "Complete 50 orders and gain the status of a harmony inspirer!",
    reward: "",
    link: "",
    level: 15,
    type: "legend_of_calmness",
  },
  {
    name_ru: "Спортивная неделя",
    name_en: "Sports Week",
    descr_ru: "Тренируйтесь 5 дней подряд без перерыва.",
    descr_en: "Train 5 consecutive days without a break.",
    reward: "",
    link: "",
    level: 15,
    type: "sports_week",
  },
  {
    name_ru: "Железный характер",
    name_en: "Iron Character",
    descr_ru: "Посвятите 50 часов тренировкам.",
    descr_en: "Dedicate 50 hours to training.",
    reward: "",
    link: "",
    level: 15,
    type: "iron_character",
  },
  {
    name_ru: "Старательный ученик",
    name_en: "Diligent Student",
    descr_ru: "Учитесь 2 часа подряд.",
    descr_en: "Study for 2 consecutive hours.",
    reward: "",
    link: "",
    level: 15,
    type: "diligent_student",
  },
  {
    name_ru: "Время для себя",
    name_en: "Time for Yourself",
    descr_ru: "Посвятите 1 час релаксации без перерывов.",
    descr_en: "Spend 1 hour on relaxation without breaks.",
    reward: "",
    link: "",
    level: 15,
    type: "time_for_yourself",
  },
  {
    name_ru: "День отдыха",
    name_en: "Rest Day",
    descr_ru:
      "Проведите 5 часов за массажем или расслабляющими активностями за день.",
    descr_en: "Spend 5 hours on massage or relaxing activities in one day.",
    reward: "",
    link: "",
    level: 15,
    type: "rest_day",
  },
]
