export default [
  {
    id: 1,
    name_ru: "Достигните 2 уровня",
    name_en: "Reach Level 2",
    descr_ru: "Сделайте первый шаг на пути к успеху.",
    descr_en: "Take the first step on your way to success.",
    reward: 100,
    link: "#",
    level: 2,
    category: "levelTask",
    category_parameters: {
      requiredLevel: 2,
    },
  },
  {
    id: 2,
    name_ru: "Новичок в обучении",
    name_en: "Training Rookie",
    descr_ru: "Завершите обучение навык 'Мотивирующий подкаст'",
    descr_en: "Complete the 'Motivational Podcast' skill",
    reward: 100,
    link: "#",
    level: 1,
    category: "learnSkillTask",
    category_parameters: {
      skillId: 1,
    },
  },
  {
    id: 3,
    name_ru: "Займись спортом",
    name_en: "Get Active",
    descr_ru: "Проведите тренировку и почувствуйте прилив позитивных эмоций!",
    descr_en: "Complete a workout andfeel the rush of positive emotions!",
    reward: 100,
    link: "#",
    level: 1,
    category: "doTrainingTask",
  },
]
