export default [
    {
      clothing_id: 1,
      name: {
        ru: "Растрепанные седые",
        en: "Windblown Ashen",
      },
      tag: [],
      type: "Hat",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_Ashen_m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_Ashen_f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_Ashen_m_-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_Ashen_f_-icon.png",
      respect: 50,
      price: 0,
      tier: 0,
    },
    {
      clothing_id: 2,
      name: {
        ru: "Растрепанные светлые",
        en: "Windblown Blonde",
      },
      tag: [],
      type: "Hat",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_Blonde_m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_Blonde_f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_Blonde_m_-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_Blonde_f_-icon.png",
      respect: 50,
      price: 0,
      tier: 0,
    },
    {
      clothing_id: 3,
      name: {
        ru: "Растрепанные темные",
        en: "Windblown brown",
      },
      tag: [],
      type: "Hat",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_brown_m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_brown_f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_brown_m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_brown_f_-icon.png",
      respect: 50,
      price: 0,
      tier: 0,
    },
    {
      clothing_id: 4,
      name: {
        ru: "Растрепанные черные",
        en: "Windblown dark",
      },
      tag: [],
      type: "Hat",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_dark_m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_dark_f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_dark_m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Head/Windblown_dark_f_-icon.png",
      respect: 50,
      price: 0,
      tier: 0,
    },
    {
      clothing_id: 5,
      name: {
        ru: "Грязная майка",
        en: "Grime Tank",
      },
      tag: ['Sport'],
      type: "Top",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Body/GrimeTank-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Body/GrimeTank-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Body/GrimeTank-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Body/GrimeTank-f-icon.png",
      respect: 0,
      price: 0,
      tier: 0,
    },
    {
      clothing_id: 6,
      name: {
        ru: "Грязные Спортивки",
        en: "Street Grind",
      },
      tag: ['Sport'],
      type: "Pants",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Legs/Street_Grind_m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Legs/Street_Grind_f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Legs/Street-Grind-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Legs/Street-Grind-f-icon.png",
      respect: 0,
      price: 0,
      tier: 0,
    },
    {
      clothing_id: 7,
      name: {
        ru: "Серые кеды",
        en: "Gray Keds",
      },
      tag: ['Sport'],
      type: "Shoes",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Shoes/M_Keds_Gray.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Shoes/F_Keds_Gray.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Shoes/Icon_M_Keds_Gray-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/0/Shoes/Icon_f_Keds_Gray-icon.png",
      respect: 0,
      price: 0,
      tier: 0,
    },
    {
      clothing_id: 8,
      name: {
        ru: "Glossy Glam dark",
        en: "Glossy Glam dark",
      },
      tag: null,
      type: "Hat",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlamDark-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlamDark-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/Glossy Glam dark-m-icon-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlamDark-f-icon.png",
      respect: 100,
      price: 50,
      tier: 1,
    },
    {
      clothing_id: 9,
      name: {
        ru: "Glossy Glam Blonde",
        en: "Glossy Glam Blonde",
      },
      tag: null,
      type: "Hat",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlamBlonde-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlamBlonde-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlamBlonde-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlamBlonde-f-icon.png",
      respect: 100,
      price: 50,
      tier: 1,
    },
    {
      clothing_id: 10,
      name: {
        ru: "Glossy Glam Brown",
        en: "Glossy Glam Brown",
      },
      tag: null,
      type: "Hat",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlam  Brown-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlamBrown-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlam  Brown-m-icon-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlamBrown-f-icon-icon.png",
      respect: 100,
      price: 50,
      tier: 1,
    },
    {
      clothing_id: 11,
      name: {
        ru: "Glossy Glam  Ashen",
        en: "Glossy Glam  Ashen",
      },
      tag: null,
      type: "Hat",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlamAshen-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlam  Ashen-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlam  Ashen-m-icon-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/GlossyGlam  Ashen-f-icon-icon.png",
      respect: 100,
      price: 50,
      tier: 1,
    },
    {
      clothing_id: 12,
      name: {
        ru: "Дреды",
        en: "Dreadlocks",
      },
      tag: null,
      type: "Hat",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/Dreadlocks-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/Dreadlocks-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/Dreadlocks-m -icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Head/Dreadlocks-f -icon.png",
      respect: 100,
      price: 1,
      tier: 0,
    },
    {
      clothing_id: 13,
      name: {
        ru: "Серая майка",
        en: "Grey tank top",
      },
      tag: "Sport",
      type: "Top",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/GreyTankTop-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/GreyTankTop-f.png.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/GreyTankTop-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/GreyTankTop-f-icon.png",
      respect: 35,
      price: 100,
      tier: 1,
    },
    {
      clothing_id: 14,
      name: {
        ru: "Майка Алкоголичка",
        en: "Wife beater",
      },
      tag: "Casual",
      type: "Top",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/WifeBeater-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/WifeBeater-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/WifeBeater-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/WifeBeater-f-icon.png",
      respect: 50,
      price: 100,
      tier: 1,
    },
    {
      clothing_id: 15,
      name: {
        ru: "Белая футболка",
        en: "White T-Shirt",
      },
      tag: "Casual",
      type: "Top",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/WhiteTShirt-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/WhiteTShirt-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/WhiteTShirt-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/WhiteTShirt-f-icon.png",
      respect: 70,
      price: 100,
      tier: 1,
    },
    {
      clothing_id: 16,
      name: {
        ru: "Огненный Пульс",
        en: "Fiery Pulse",
      },
      tag: null,
      type: "Top",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/FieryPulse-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/FieryPulse-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/FieryPulse-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/FieryPulse-f-icon.png",
      respect: 70,
      price: 100,
      tier: 1,
    },
    {
      clothing_id: 17,
      name: {
        ru: "Жаркая Волна",
        en: "Heat Wave",
      },
      tag: null,
      type: "Top",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/HeatWave-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/HeatWave-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/HeatWave-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Body/HeatWave-f-icon.png",
      respect: 70,
      price: 100,
      tier: 1,
    },
    {
      clothing_id: 18,
      name: {
        ru: "Рабочие штаны",
        en: "Work Pants",
      },
      tag: ["Casual"],
      type: "Pants",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/WorkPants-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/WorkPants-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/WorkPants-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/WorkPants-f-icon.png",
      respect: 50,
      price: 450,
      tier: 1,
    },
    {
      clothing_id: 19,
      name: {
        ru: "Дешевые джинсы",
        en: "Supermarket jeans",
      },
      tag: ["Casual"],
      type: "Pants",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/SupermarketJeans-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/SupermarketJeans-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/SupermarketJeans-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/SupermarketJeans- f-icon.png",
      respect: 30,
      price: 350,
      tier: 1,
    },
    {
      clothing_id: 20,
      name: {
        ru: "Чистые спортивки",
        en: "Clean Sweatpants",
      },
      tag: ["Casual"],
      type: "Pants",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/CleanSweatpants-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/CleanSweatpants-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/CleanSweatpants-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Legs/CleanSweatpants-f-icon.png",
      respect: 100,
      price: 430,
      tier: 1,
    },
    {
      clothing_id: 21,
      name: {
        ru: "Черные кеды",
        en: "Black Keds",
      },
      tag: null,
      type: "Shoes",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Shoes/BlackKeds-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Shoes/BlackKeds-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Shoes/BlackKeds-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Shoes/BlackKeds-f-icon.png",
      respect: 50,
      price: 500,
      tier: 1,
    },
    {
      clothing_id: 22,
      name: {
        ru: "Трудяга",
        en: "Workaholic",
      },
      tag: null,
      type: "Accessory",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Accessories/Workaholic-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Accessories/Workaholic-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Accessories/Workaholic-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/1/Accessories/Workaholic-f-icon.png",
      respect: 100,
      price: 300,
      tier: 1,
    },
    {
      clothing_id: 23,
      name: {
        ru: "Sharp Finish ashen",
        en: "Sharp Finish ashen",
      },
      tag: null,
      type: "Hat",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/2/Head/SharpFinishAshen-m .png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/2/Head/SharpFinishAshen-f .png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/2/Head/SharpFinishAshen-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/2/Head/SharpFinishAshen-f-icon.png",
      respect: 100,
      price: 100,
      tier: 2,
    },
    {
      clothing_id: 24,
      name: {
        ru: "Sharp Finish blondie",
        en: "Sharp Finish blondie",
      },
      tag: null,
      type: "Hat",
      effect: null,
      male_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/2/Head/SharpFinishBlondie-m.png",
      female_link: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/2/Head/SharpFinishBlondie-f.png",
      male_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/2/Head/SharpFinishBlondie-m-icon.png",
      female_icon: "https://d8bddedf-ac40-4488-8101-05035bb63d25.selstorage.ru/clothes/2/Head/SharpFinishBlondie-f-icon.png",
      respect: 100,
      price: 100,
      tier: 2,
    },
    // {
    //   clothing_id: 25,
    //   name: {
    //     ru: "Sharp Finish brown",
    //     en: "Sharp Finish brown",
    //   },
    //   tag: null,
    //   type: "Hat",
    //   effect: null,
    //   male_link: "/placeholders/male/sharp-finish-brown-hat.jpg",
    //   female_link: "/placeholders/female/sharp-finish-brown-hat.jpg",
    //   respect: 100,
    //   price: 100,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 26,
    //   name: {
    //     ru: "Sharp Finish dark",
    //     en: "Sharp Finish dark",
    //   },
    //   tag: null,
    //   type: "Hat",
    //   effect: null,
    //   male_link: "/placeholders/male/sharp-finish-dark-hat.jpg",
    //   female_link: "/placeholders/female/sharp-finish-dark-hat.jpg",
    //   respect: 100,
    //   price: 100,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 27,
    //   name: {
    //     ru: "Хулиган",
    //     en: "Bully",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/bully-top.jpg",
    //   female_link: "/placeholders/female/bully-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 28,
    //   name: {
    //     ru: "Кочевник",
    //     en: "Nomad",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/nomad-top.jpg",
    //   female_link: "/placeholders/female/nomad-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 29,
    //   name: {
    //     ru: "Серый Бродяга",
    //     en: "Grey Tramp",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/grey-tramp-top.jpg",
    //   female_link: "/placeholders/female/grey-tramp-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 30,
    //   name: {
    //     ru: "Тень",
    //     en: "Shadow",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/shadow-top.jpg",
    //   female_link: "/placeholders/female/shadow-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 31,
    //   name: {
    //     ru: "Классика",
    //     en: "Classic",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/classic-top.jpg",
    //   female_link: "/placeholders/female/classic-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 32,
    //   name: {
    //     ru: "Черное на красном",
    //     en: "Black & Red",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/black-and-red-top.jpg",
    //   female_link: "/placeholders/female/black-and-red-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 33,
    //   name: {
    //     ru: "Гот",
    //     en: "Goth",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/goth-top.jpg",
    //   female_link: "/placeholders/female/goth-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 34,
    //   name: {
    //     ru: "Нежность",
    //     en: "Softness",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/softness-top.jpg",
    //   female_link: "/placeholders/female/softness-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 35,
    //   name: {
    //     ru: "Эко",
    //     en: "Eco",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/eco-top.jpg",
    //   female_link: "/placeholders/female/eco-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 36,
    //   name: {
    //     ru: "Лайм",
    //     en: "Lime",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/lime-top.jpg",
    //   female_link: "/placeholders/female/lime-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 37,
    //   name: {
    //     ru: "Красный",
    //     en: "Red",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/red-top.jpg",
    //   female_link: "/placeholders/female/red-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 38,
    //   name: {
    //     ru: "Дизель",
    //     en: "Diesel",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/diesel-top.jpg",
    //   female_link: "/placeholders/female/diesel-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 39,
    //   name: {
    //     ru: "Блекаут",
    //     en: "Blackout",
    //   },
    //   tag: null,
    //   type: "Top",
    //   effect: null,
    //   male_link: "/placeholders/male/blackout-top.jpg",
    //   female_link: "/placeholders/female/blackout-top.jpg",
    //   respect: 70,
    //   price: 200,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 40,
    //   name: {
    //     ru: "Серый графит",
    //     en: "Grey graphite",
    //   },
    //   tag: null,
    //   type: "Pants",
    //   effect: null,
    //   male_link: "/placeholders/male/grey-graphite-pants.jpg",
    //   female_link: "/placeholders/female/grey-graphite-pants.jpg",
    //   respect: 50,
    //   price: 350,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 41,
    //   name: {
    //     ru: "Джинсовые шорты",
    //     en: "Denim Shorts",
    //   },
    //   tag: null,
    //   type: "Pants",
    //   effect: null,
    //   male_link: "/placeholders/male/denim-shorts.jpg",
    //   female_link: "/placeholders/female/denim-shorts.jpg",
    //   respect: 50,
    //   price: 350,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 42,
    //   name: {
    //     ru: "Черыне шорты",
    //     en: "Black Shorts",
    //   },
    //   tag: null,
    //   type: "Pants",
    //   effect: null,
    //   male_link: "/placeholders/male/black-shorts.jpg",
    //   female_link: "/placeholders/female/black-shorts.jpg",
    //   respect: 50,
    //   price: 350,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 43,
    //   name: {
    //     ru: "Короткий Шик",
    //     en: "Short Chic",
    //   },
    //   tag: null,
    //   type: "Pants",
    //   effect: null,
    //   male_link: "/placeholders/male/short-chic-pants.jpg",
    //   female_link: "/placeholders/female/short-chic-pants.jpg",
    //   respect: 50,
    //   price: 350,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 44,
    //   name: {
    //     ru: "Верблюжьи Штаны",
    //     en: "Camel Pants",
    //   },
    //   tag: null,
    //   type: "Pants",
    //   effect: null,
    //   male_link: "/placeholders/male/camel-pants.jpg",
    //   female_link: "/placeholders/female/camel-pants.jpg",
    //   respect: 50,
    //   price: 350,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 45,
    //   name: {
    //     ru: "Брюки из секонхенда",
    //     en: "Second-hand trousers",
    //   },
    //   tag: null,
    //   type: "Pants",
    //   effect: null,
    //   male_link: "/placeholders/male/second-hand-trousers.jpg",
    //   female_link: "/placeholders/female/second-hand-trousers.jpg",
    //   respect: 50,
    //   price: 350,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 46,
    //   name: {
    //     ru: "Тактикульщик",
    //     en: "Tactician",
    //   },
    //   tag: null,
    //   type: "Pants",
    //   effect: null,
    //   male_link: "/placeholders/male/tactician-pants.jpg",
    //   female_link: "/placeholders/female/tactician-pants.jpg",
    //   respect: 50,
    //   price: 350,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 47,
    //   name: {
    //     ru: "Дерби",
    //     en: "Derby",
    //   },
    //   tag: null,
    //   type: "Shoes",
    //   effect: null,
    //   male_link: "/placeholders/male/derby-shoes.jpg",
    //   female_link: "/placeholders/female/derby-shoes.jpg",
    //   respect: 100,
    //   price: 700,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 48,
    //   name: {
    //     ru: "Purple Edge",
    //     en: "Purple Edge",
    //   },
    //   tag: null,
    //   type: "Shoes",
    //   effect: null,
    //   male_link: "/placeholders/male/purple-edge-shoes.jpg",
    //   female_link: "/placeholders/female/purple-edge-shoes.jpg",
    //   respect: 100,
    //   price: 700,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 49,
    //   name: {
    //     ru: "Обычные очки",
    //     en: "Ordinary Glasses",
    //   },
    //   tag: null,
    //   type: "Accessories",
    //   effect: null,
    //   male_link: "/placeholders/male/ordinary-glasses.jpg",
    //   female_link: "/placeholders/female/ordinary-glasses.jpg",
    //   respect: 200,
    //   price: 1000,
    //   tier: 2,
    // },
    // {
    //   clothing_id: 50,
    //   name: {
    //     ru: "Серебрянная серьга",
    //     en: "Silver Earring",
    //   },
    //   tag: null,
    //   type: "Accessories",
    //   effect: null,
    //   male_link: "/placeholders/male/silver-earring.jpg",
    //   female_link: "/placeholders/female/silver-earring.jpg",
    //   respect: 200,
    //   price: 1000,
    //   tier: 2,
    // },
  ]
  